### ISSUE TITLE
santiago's furry ass

### ISSUE THREAD

**Issue by kzrc** [cerealwithmilk/olympia#3]
bro used pyinstaller and thought he was elite

**Comment by cerealwithmilk** [comment]
you are retarded by mentioning an public name that i had on my github
also, i didn't release this, this was an leak dumbass.

**Comment by kzrc** [comment]
late ass leak lmao, also literally v1 so it doesnt matter. this is the most useless thing youve done santi, even after people called you the messiah for learning how to use the microsoft store to downgrade and network intercepting....

you are completely useless and thats why fluster never dropped

**Comment by kzrc** [comment]
you edited 3 times and still didnt fix your spelling error. damn bro

**Comment by cerealwithmilk** [comment]
> late ass leak lmao, also literally v1 so it doesnt matter. this is the most useless thing youve done santi, even after people called you the messiah for learning how to use the microsoft store to downgrade and network intercepting....
> 
> you are completely useless and thats why fluster never dropped

might be, but i don't think you managed to make something similar, didn't you? :)
